name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest
      
    env:
      working-directory: ./ferris_clock

    steps:
    - uses: actions/checkout@v2
    - name: Flutter Build
      uses: subosito/flutter-action@v1
      with:
        channel: 'master'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{env.working-directory}}
#     - name: Run tests
#       run: flutter test
#       working-directory: ${{env.working-directory}}
    - name: Build Web
      run: |
        flutter build web
        flutter config --enable-web
      working-directory: ${{env.working-directory}}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ferris_clock
        # Directory containing files to upload
        path: ${{env.working-directory}}/build/web
