name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
#     - name: Run tests
#       run: pub run test
    - name: Enable web
      run: flutter config --enable-web
    - name: Build web
      run: flutter build web
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: index.html
        # Directory containing files to upload
        path: build/web
