name: Flutter CI

on:
  push:
    branches:
      - master
    paths:
      - ferris_clock/lib/*
      - ferris_clock/test/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ferris_clock
    
    steps:
    - uses: actions/checkout@v2
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{env.working-directory}}
#     - name: Run tests
#       run: flutter test
#       working-directory: ${{env.working-directory}}
    - name: Build Web
      run: |
        flutter config --enable-web
        flutter build web
      working-directory: ${{env.working-directory}}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ferris_clock
        # Directory containing files to upload
        path: ${{env.working-directory}}/build/web
    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ${{env.working-directory}}/build/web  
